#server:
#  port: 8080
#  servlet:
#    context-path: /
#    encoding:
#      charset: utf-8
#      enabled: true
#    session:
#      timeout: 60m

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/intell?serverTimezone=Asia/Seoul
    username: intell
    password: intell1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  #    show-sql: true
  #    properties:
  #      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false